package akka.dispatch

import akka.actor.Cell
import protocol.MessageId

/**
  * These events are generated by the dispatcher
  */
sealed abstract class ProgramEvent

case class ActorCreated(actor: Cell) extends ProgramEvent
case class ActorDestroyed(actor: Cell) extends ProgramEvent

/** A fresh message is sent **/
case class MessageSent(receiver: Cell, msg: Envelope) extends ProgramEvent
/** Message with id is received **/
case class MessageReceived(receiver: Cell, id: MessageId, msg: Envelope) extends ProgramEvent
/** Message with id is dropped **/
case class MessageDropped(receiver: Cell, id: MessageId, msg: Envelope) extends ProgramEvent

/** As the initial event to be sent and also to be used in tests **/
case object DummyProgramEvent extends ProgramEvent


object ProgramEvent {
  def areRacyEvents(e1: ProgramEvent, e2: ProgramEvent): Boolean = !e1.equals(e2) && getActor(e1) == getActor(e2)

  def getActor(e: ProgramEvent): Cell = e match {
    case e: ActorCreated =>  e.asInstanceOf[ActorCreated].actor
    case e: ActorDestroyed =>  e.asInstanceOf[ActorDestroyed].actor
    case e: MessageDropped =>  e.asInstanceOf[MessageDropped].receiver
    case e: MessageReceived =>  e.asInstanceOf[MessageReceived].receiver
    case e: MessageSent =>  e.asInstanceOf[MessageSent].receiver
    case _ =>
      println("Unexpected program event: " + e)
      null
  }

  def getContent(e: ProgramEvent): String = e match {
    case e: ActorCreated =>  ""
    case e: ActorDestroyed =>  ""
    case e: MessageDropped =>  e.asInstanceOf[MessageDropped].msg.message.toString
    case e: MessageReceived =>  e.asInstanceOf[MessageReceived].msg.message.toString
    case e: MessageSent =>  e.asInstanceOf[MessageSent].msg.message.toString
    case _ =>
      println("Unexpected program event: " + e)
      ""
  }
}